"""empty message

Revision ID: 0d15224aaa7e
Revises: 
Create Date: 2018-12-07 16:51:47.675622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d15224aaa7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('platenumber', sa.String(length=255), nullable=False),
    sa.Column('car_name', sa.String(length=255), nullable=False),
    sa.Column('car_type', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('platenumber')
    )
    op.create_table('records',
    sa.Column('records_id', sa.String(length=255), nullable=False),
    sa.Column('platenumber', sa.String(length=255), nullable=True),
    sa.Column('path_in_id', sa.Integer(), nullable=True),
    sa.Column('path_in_time', sa.DateTime(), nullable=True),
    sa.Column('path_out_id', sa.String(length=255), nullable=True),
    sa.Column('path_out_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('records_id')
    )
    op.create_table('station',
    sa.Column('station_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.String(length=255), nullable=False),
    sa.Column('station_status', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('station')
    op.drop_table('records')
    op.drop_table('car')
    # ### end Alembic commands ###
